### ISSUE TITLE
Feedback técnico

### ISSUE THREAD

**Issue by RuthSalvador** [julissarosmery/lim-2018-05-bc-core-am-cipher#1]
# Recomendaciones de mejora 👍

- **`README.md`**: buena idea presentar como te organizaste durante estos 2 sprints, imágenes de la evolución de tu producto, recuerda adicionar las tecnologías que utilizaste, así como la imagen del proyecto terminado.

- **`index.html`**: recuerda que debes validar tu `html`, te recomendamos revisar el enlace https://validator.w3.org/nu/?doc=https%3A%2F%2Fjulissarosmery.github.io%2Flim-2018-05-bc-core-am-cipher%2Fsrc%2F  para mayor especificación. Te sugerimos utilizar más etiquetas semánticas como `header`, `figure`. En cuanto al nombre de tus `id` y `class` puedes usar la sintaxis con guiones en lugar de camelCase (éste se usa más para las variables en `javascript`). Ej:
  ``` js
  const textInput = document.getElementById('text-input');
  ```
  Cuida tu indentación. 

- **`cipher.js`**: buena lógica para las operaciones de cifrado y descifrado. Ten cuidado con tu indentación`. Te recomendamos utilizar `for of` para utilizar la nueva sintaxis de `ES6`. Evita usar variables no descriptivas como `a`, `x`; recuerda que deben ser descriptivas. Puedes refactorizar tu código utilizando una sola variable `result` e ir almacenando directamente ahí en lugar de almacenarlo en code y luego unirlo.
  ```js
  if (string.charCodeAt(i) >= 65 && string.charCodeAt(i) <= 90) {
    result += String.fromCharCode((((string.charCodeAt(i) - 65) + offset) % 26) + 65);
  } else ...
  ```

- **`index.js`**: recuerda declarar tus variables con nombres en inglés y descriptivas, puedes declararlas al inicio y luego llamarlas cuando las necesites.

- **`style.css`**: recuerda utilizar clases descriptivas y nombralas en inglés; te recomendamos crear clases para reutilizar estilos.

- **Tests**: bien siempre apuntar a una cobertura de 100%, recuerda que si deseas puedes agregar más tests para practicar.

Por último te recomendamos tener en cuenta la guía de estilos y utilizar comillas simples (' ') en archivos `js` y comillas dobles (" ") en el `html`. Además los usuarios deben ver tu producto desde cualquier dispositivo, por lo que te recomendamos realizar tus proyectos responsive.
Recuerda declarar tus variables, clases, id con nombres en inglés y descriptivas; y cuidar tu indentación la cual debe ser de 2 espacios para todos los archivos.
No te olvides llegar a los niveles esperados en Github.

Sigue así buen trabajo 👍

**Comment by julissarosmery** [comment]
muchas gracias
